# build stage
FROM golang:alpine AS build-env
ADD main.go /src/main.go
ADD ./vendor/github.com/pusher/pusher-http-go /go/src/github.com/pusher/pusher-http-go
RUN cd /src && go build -o goapp

# final stage
FROM alpine
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
WORKDIR /app
COPY --from=build-env /src/goapp /app/
CMD ./goapp
